### ISSUE TITLE
Is this still active?

### ISSUE THREAD

**Issue by bar9** [namuol/cod#7]
Hi there

Would be interested in maintaining this and using it as a basis for a language-agnostic docgen tool.

What's your status?

**Comment by namuol** [comment]
Thanks for your interest - unfortunately I am no longer actively maintaining the project, but as far as I know it was never used outside my own personal projects. Please give it a try and let me know if you have any success getting it working! It might be worth porting over to standard JS at least.

**Comment by jaames** [comment]
Heya! Cod seemed like the perfect documentation tool for a project I'm currently working on, so I took it upon myself to rewrite it over the weekend since I couldn't get it to run under modern Node versions.

My fork is at https://github.com/jaames/cod

I just focused on my requirements, as such it's missing a few features like streaming support and some of the advanced tag stuff, but I've rewritten it in Typescript and removed the peg.js based parser to hopefully make it a little easier for other people to contribute if they want!

**Comment by namuol** [comment]
@jaames That's awesome! Thank you for your interest and for sharing your work here.

Some notes:

- I [updated the readme](https://github.com/namuol/cod/commit/eb7e976a9598c05f7c7795887e172a4e76a30f11) to mention that this project is not actively maintained.
- I linked to @jaames' rewrite as a possible alternative for anyone who stumbles upon the project.

I'm this issue since I've formally updated the readme to answer this question. Thanks again for your interest!

**Comment by jaames** [comment]
Oh sweet, thanks @namuol! 

Would you mind if I also rehosted the documentation site with some edits? I want to make sure I'm not stepping on any toes. :)

**Comment by namuol** [comment]
> Would you mind if I also rehosted the documentation site with some edits? I want to make sure I'm not stepping on any toes. :)

Oh sure, do whatever you want! Step away!
